trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  sshConnection: 'azure-vm-ssh'

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: $(sshConnection)
    sourceFolder: '.'
    contents: '**'
    targetFolder: '/home/ubuntu/mean-app'
    overwrite: true

- task: SSH@0
  inputs:
    sshEndpoint: $(sshConnection)
    runOptions: 'commands'
    commands: |
      cd /home/ubuntu/mean-app
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
      pm2 stop all || true
      pm2 start backend/server.js --name backend --watch
      sudo cp -r frontend/dist/* /var/www/html
